@workdir@inflection.a:  @workdir@inflection/adjectiveinfl.a  @workdir@inflection/adverbinfl.a  @workdir@inflection/indeclinfl.a @workdir@inflection/infininfl.a  @workdir@inflection/nouninfl.a  @workdir@inflection/ptcplinfl.a @workdir@inflection/vadjinfl.a  @workdir@inflection/verbinfl.a @workdir@inflection/irreginfl.a 
%.a: %.fst
	fst-compiler $< $@
